name: Auto-update Charm Libraries on merge
on:
  push:  # merges on main
  
jobs:
  release-libs:
    name: Auto-release any bumped libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Check libraries
        uses: PietroPasotti/charming-actions/release-libraries@release-libs
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

